language: haxe

haxe:
  - 3.2.1
  - development

os:
  - linux
  - osx

matrix:
  # Allow Haxe development to fail.
  allow_failures:
    - haxe: development

sudo: false
addons:
  apt:
    packages:
      # Python
      - python3
      # PHP
      - php5-cli
      # C#
      - mono-devel
      - mono-mcs

install:
  # os-specific config
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update;
      brew install mono;
      brew install python3;
    fi
  # Install haxelibs
  - haxelib install hxcpp
  - haxelib install hxjava
  - haxelib install hxcs
  - haxelib list

script:
  - haxe -main Test -cp test -debug --interp
  - haxe -main Test -cp test -debug -neko bin/Test.n          && neko bin/Test.n
  - haxe -main Test -cp test -debug -js bin/Test.js           && node bin/Test.js
  - haxe -main Test -cp test -debug -php bin                  && php bin/index.php
  - haxe -main Test -cp test -debug -java bin                 && java -jar bin/Test-Debug.jar
  - haxe -main Test -cp test -debug -cs bin -D erase-generics && mono bin/bin/Test-Debug.exe
  - haxe -main Test -cp test -debug -python bin/Test.py       && python3 bin/Test.py
  - haxe -main Test -cp test -debug -cpp bin -dce full        && ./bin/Test-debug
