language: node_js

before_script:
  - sudo apt-get install python-software-properties -y # for the next command
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y
  - mkdir ~/haxelib && haxelib setup ~/haxelib
  - sudo apt-get install php5 -y
  - sudo apt-get install gcc-multilib g++-multilib -y  # for hxcpp
  - haxelib install hxcpp

script:
  - haxe -main Test -cp test -debug --interp
  - haxe -main Test -cp test -debug -neko Test.n && neko Test.n
  - haxe -main Test -cp test -debug -js Test.js && node -e "var Test = require('./Test.js').Test; Test.main(); process.exit(Test.success ? 0 : 1);"
  - haxe -main Test -cp test -debug -php bin && php bin/index.php
  - haxe -main Test -cp test -debug -cpp bin -dce full && ./bin/Test-debug