name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    strategy:
      matrix:
        container:
          - "haxe:4.2"
          - "haxe:4.1"
          - "haxe:4.0"
          - "haxe:3.4"
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - name: setup haxelib
        run: |
          set -ex
          haxelib newrepo
          haxelib install test.hxml
      - name: test
        run: haxe test.hxml
